### ISSUE TITLE
number of records in the queue

### ISSUE THREAD

**Issue by chinhtrandn** [SMFSW/Queue#14]
Hello,
It work fine if set nb_recs < 40. can you let me know maximum of nb_recs. Thank you

**Comment by SMFSW** [comment]
There is no limit to say so...

It totally depends:
- MCU heap size
- MCU heap size already used by the project you're implementing `Queue` into
- The size of a `Queue` record

Anyways, after the `Queue` constructor ran, you can use `isInitialized` method on your `Queue` class to check if the dynamic allocation succeeded, thus ensuring your class is totally initialized and usable.
