### ISSUE TITLE
print all members of a static queue

### ISSUE THREAD

**Issue by armando-fandango** [SMFSW/Queue#22]
how to print all the members of a static queue without deleting them from queue

**Comment by SMFSW** [comment]
A mix of methods below will do.

`q.getCount()` or `q.nbRecs()`: number of records stored in the queue

Peek stuff at index from the queue using `q.peekIdx(void * rec, uint16_t idx)`
    returns `true` if successfully peeked from queue
    returns `false` if index is out of range
