### ISSUE TITLE
Esp32 compatibility

### ISSUE THREAD

**Issue by wiryonolau** [SMFSW/Queue#23]
Hi,

Is this library works with esp32 ?

Our process is 
1. Using Wire.onReceive to get data from other controller.
2. Push data to queue
3. On the void loop we retrieve the data from queue do a bit manipulation and send to server

Is this process possible ?

**Comment by SMFSW** [comment]
Hello,

Some time ago, there was an issue with esp as there was already a class with the same name in the BSP, but it is fixed now, so `Queue` should be compatible.

This is a pretty basic processing, so everything should work fine.
Just beware if you push to the queue from interrupts... you shall disable interrupts when pulling from the queue in you main loop (but it doesn't seem to be the case here).

Thanks for your interest in `Queue` library.
Regards,
SMFSW
