### ISSUE TITLE
Publish Doxygen doc to GitHub pages

### ISSUE THREAD

**Issue by s-celles** [SMFSW/Queue#6]
Hello,

It will be nice to publish Doxygen doc to GitHub pages.
Doc can be updated automatically using Travis.
https://www.google.fr/search?q=deploy+Doxygen+documentation+with+Travis+CI

Kind regards

**Comment by s-celles** [comment]
Sorry I've just noticed
https://github.com/SMFSW/Queue/blob/70b5436e780243a6eea39f17e772eac702c90685/.travis.yml#L24

So link to published doc in README will be great

**Comment by SMFSW** [comment]
I leave the issue open, generated doc is empty yet...
I'll check that out

**Comment by s-celles** [comment]
Thanks for the great work.
Call graph of functions with graphviz is a nice feature of Doxygen!
